#!/usr/bin/env php
<?php

/**
 * ModernWeb
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.modernweb.pl/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to kontakt@modernweb.pl so we can send you a copy immediately.
 *
 * @category    Modern
 * @package     Modern_Application
 * @subpackage  Bootstrap
 * @author      Rafał Gałka <rafal@modernweb.pl>
 * @copyright   Copyright (c) 2007-2012 ModernWeb (http://www.modernweb.pl)
 * @license     http://www.modernweb.pl/license/new-bsd     New BSD License
 */

/**
 * CLI application bootstrap script
 *
 * @category    Modern
 * @package     Modern_Application
 * @subpackage  Bootstrap
 * @author      Rafał Gałka <rafal@modernweb.pl>
 * @copyright   Copyright (c) 2007-2012 ModernWeb (http://www.modernweb.pl)
 */

$root = realpath(dirname(__FILE__) . '/../');
$env = $root . '/application/configs/env.php';
require_once((is_readable($env)) ? $env : $env . '.dist');

/** Modern_Application */
require_once 'Modern/Application.php';

// Create application, bootstrap, and run
$application = new Modern_Application(
    ENVIRONMENT,
    APPLICATION_PATH . '/configs/application.ini'
);
$application->bootstrap();

require 'vendor/zendframework/zendframework1/bin/zf.php';
