<?= $this->doctype() . "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml" <?php /*
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="https://www.facebook.com/2008/fbml"
      */?> lang="pl">
<head>
    <?= $this->headMeta()->setSeparator(PHP_EOL . '    ')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=Edge,chrome=1')
        ->appendName('description', '')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    . "\n" ?>

    <?= $this->headTitle('Project Name')->setSeparator(' - ') . "\n" ?>

    <?= $this->headLink()->setSeparator(PHP_EOL . '    ')
        ->appendStylesheet('/assets/build/styles/app.css')
    . "\n" ?>

    <link rel="shortcut icon" href="/assets/favicon.ico">
</head>

<body>
    <?= $this->render('includes/header.phtml') ?>

    <div class="container">
        <?=$this->layout()->content?>

        <?= $this->render('includes/footer.phtml') ?>
    </div>

    <script src="/assets/build/scripts/app.js"></script>
</body>
</html>
