<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <h1>Hello, world!</h1>

    <p>This is a template for a simple marketing or informational website. It includes a large
        callout called the hero unit and three supporting pieces of content. Use it as a starting
        point to create something more unique.</p>

    <p><a class="btn btn-lg btn-success">Learn more &raquo;</a></p>
</div>

<!-- Example row of columns -->
<div class="row">
    <section class="col-md-8">
        <header>
            <h2>Sprite test</h2>
        </header>
        <article>
            <p class="sprite-test"></p>

            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus
                commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
                Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
            <p>
                <a class="btn btn-primary" href="#" role="button">
                    View details
                    <i class="fa fa-angle-double-right"></i>
                </a>
            </p>
        </article>
    </section>
    <section class="col-md-4">
        <header>
            <h2>Sidebar Heading</h2>
        </header>
        <article>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus
                commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
                Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
            <p>
                <a class="btn btn-primary" href="#" role="button">
                    View details <i class="fa fa-angle-double-right"></i></a>
            </p>
        </article>
    </section>
</div>
