<?= $this->doctype() . "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="https://www.facebook.com/2008/fbml"
      lang="pl">
<head>
    <?= $this->headMeta()->setSeparator(PHP_EOL . '    ')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=Edge,chrome=1')
        ->appendName('description', '')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    . "\n" ?>

    <?= $this->headTitle('Project Name')->setSeparator(' - ') . "\n" ?>

    <?= $this->headLink()->setSeparator(PHP_EOL . '    ')
        ->appendStylesheet('/static/css/website.min.css')
    . "\n" ?>

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="/favicon.ico">
    <?php /* <link rel="apple-touch-icon" href="/public/static/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/public/static/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/public/static/images/apple-touch-icon-114x114.png"> */ ?>

</head>

<body>

    <div class="container">
        <?=$this->layout()->content?>
    </div>

    <script src="/public/assets/javascripts/desktop.min.js"></script>

</body>
</html>
